# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests
env:
  # SUBGRAPH_URL: "http://140.82.62.189:8000/subgraphs/name/sir-trade/index"
  # RPC_URL: "http://140.82.62.189:8545"
  # NEXT_PUBLIC_APE_HASH: "0xab441bacf05ed03fed44203a396ee50d93c56e0e0165d7e80561eb77d410369c"
  # NEXT_PUBLIC_SIR_ADDRESS: "0x7A3A9876c08B3f001D10c6a8aF685699BC52e7c8"
  # NEXT_PUBLIC_ASSISTANT_ADDRESS: "0x02d6db176f10C4FdceBDD1B44c1037c1B568bc2E"
  # NEXT_PUBLIC_VAULT_ADDRESS: "0x76d05F58D14c0838EC630C8140eDC5aB7CD159Dc"
  # NEXT_PUBLIC_CHAIN_ID: "1"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  tests-and-check-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH:$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test

      - name: Check Types
        run: pnpm run ts-lint
